### ISSUE TITLE
[Bug]firework rocket dosen't boost flying with elytra

### ISSUE THREAD

**Issue by 1950694292** [ACGaming/UniversalTweaks#94] opened 2023-03-10 02:26 UTC
only UniversalTweaks installed 
default config

**Comment by ACGaming** [comment] 2023-03-10 13:44
Please try to determine the tweak that‘s causing the behaviour, thank you!

**Comment by ACGaming** [comment] 2023-03-11 07:58
It is, thanks for the research! Since this was borrowed from VanillaFix, it‘s the same issue as DimensionalDevelopment/VanillaFix#138.
Can‘t imagine why this issue is related to the tweak, going to make it opt-in for now.

**Comment by jchung01** [comment] 2023-03-31 20:51
It looks like it has to do with this [vanilla issue](https://bugs.mojang.com/browse/MC-111480) that was fixed in MC 1.14+ by changing the firework entity's `BOOSTED_ENTITY_ID` to use `OptionalInt` instead of `Integer`, so it would take quite a bit of work to backport the fix. I assume the fast world loading tweak just makes the bug consistently reproducible because it probably ensures the player is the first entity loaded by not loading the initial chunks first.

**Comment by ACGaming** [comment] 2023-04-01 06:36
Great insight! Didn‘t know about this check, but it makes a lot of sense now.

**Closed** 2023-04-01 08:35 UTC
Labels: bug
