### ISSUE TITLE
Invalid Mixin Exception Error on server. 

### ISSUE THREAD

**Issue by whatsapp2** [ACGaming/UniversalTweaks#595] opened 2024-11-24 01:15 UTC
My friends and I made a kitchen sink modpack and added universal tweaks to it. 
Our consoles keep getting spammed with this error.

https://gist.github.com/whatsapp2/268062641777cebff91bd85faeb10715

If anything else is required to submit the report let me know

**Comment by ACGaming** [comment] 2024-11-24 10:27
Is it really caused by Universal Tweaks?

From the log, it's Had Enough Items complaining about Minecraft Transport Simulator's JEI interface.

**Comment by whatsapp2** [comment] 2024-11-27 05:01
I am actually not too sure, it mentioned Universal Tweaks to I figured I would post here... Either way I have to relay this to MTS devs, see what they can find and I'll report back

**Comment by whatsapp2** [comment] 2024-11-27 08:13
I mentioned this issue to MTS dev, hasn't answered at the time of writting this message, but when I was checking my latest.log to see if I got any other error I found this

`Mixin apply for mod universaltweaks failed mixins.tweaks.misc.buttons.anaglyph.json:UT3DAnaglyphMixin from owner universaltweaks -> net.minecraft.client.gui.GuiVideoSettings`

Here's the full log
https://gist.github.com/whatsapp2/ca8cd2f5000cda511a9146cfbc19b45b

**Comment by ACGaming** [comment] 2024-11-27 12:10
That's just the 3D Anaglyph button tweak failing silently because OptiFine is installed, nothing to worry about.

**Comment by DonBruce64** [comment] 2024-12-14 04:21
This is indeed a bug with IV.  Y'all can close it out and I'll handle it on my end..

**Closed** 2024-12-14 19:34 UTC
Labels: bug, question
