### ISSUE TITLE
Game crashes when flying and holding Shift and Space near ChickensMod Henhouse block

### ISSUE THREAD

**Issue by Biliniko** [ACGaming/UniversalTweaks#533] opened 2024-08-07 08:57 UTC
**Description**:
The crash occurs specifically when I'm flying, holding Shift and Space simultaneously, and my character's head touches the Henhouse block from the ChickensMod (https://github.com/setycz/ChickensMod).

**Steps to Reproduce**:
1. Only load the ChickensMod and Universal Tweaks.
2. Start flying and hold Shift and Space at the same time.
3. Make your character's head collide with a Henhouse block from the ChickensMod.

**The game crashes with the following error**:

```
java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.BufferBuilder.func_181668_a(BufferBuilder.java:309)
	at net.minecraft.client.renderer.RenderGlobal.func_189694_a(RenderGlobal.java:2862)
	at net.minecraft.client.renderer.RenderGlobal.func_189697_a(RenderGlobal.java:2855)
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2840)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1829)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
```

**Additional Information**:
- Universal Tweaks version: 1.11.0
- ChickensMod version: 6.1.0

Thank you for your help!

**Comment by ACGaming** [comment] 2024-08-07 16:29
This might be the most specific issue so far, hats off!

**Comment by jchung01** [comment] 2024-08-28 23:42
I was unable to reproduce a crash with just Chickens and UT with the henhouse block, _but_ this sort of crash did happen with the roost block from the Roost mod. The crash with _roosts_ should be fixed with the above PR. I suspect the user mistook the roost as the henhouse, but if you can reproduce the crash with specifically the henhouse, then this is still an issue.

**Closed** 2024-08-29 05:51 UTC
Labels: bug
