### ISSUE TITLE
The Bugfix "Block Overlay" possibly causing the client to crash

### ISSUE THREAD

**Issue by AllenAlien920** [ACGaming/UniversalTweaks#547] opened 2024-08-28 15:49 UTC
### Game Version
Java: 8u421
Minecraft: 1.12.2
Forge: 14.23.5.2860
Mod Version: UniversalTweaks 1.7.1, [AE2 Unofficial Extended Life v0.56.4](https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life)
### Description
The game crashes when I tried teleporting through an Applied Energistics' ME drive with an EnderIO's staff of travelling. Also, if you use command to setblock an ME drive on your head, the game crashes again.
### Step to reproduce
1. Create a new version with AE2 and Universal Tweaks being the only mods
2. Create a new world
3. Enter the command: `/setblock ~ ~1 ~ appliedenergistics2:drive`
4. The game crashes
### Crash report
[crash-2024-08-28_23.15.01-client.txt](https://github.com/user-attachments/files/16785678/crash-2024-08-28_23.15.01-client.txt)
### Additional context
It seems that this crash has the same cause as #533, where your head enters a transparent block in other mods results in the crash.

**Comment by AllenAlien920** [comment] 2024-08-28 15:55
If the "Block Overlay Toggle" is disabled in the config file, the bug doesn't happen, so I think that this feature has something to do with the crash.

**Comment by jchung01** [comment] 2024-08-28 22:21
Looks like the issue was a rendering issue on AE2-UEL's side, it's just that the block overlay fix happens to trigger the issue. The ME Drive has already been blacklisted on UT's side in #526 for next update, but this issue was fixed on AE2-UEL's side in v0.56.5 (see AE2-UEL/Applied-Energistics-2#420). The blacklist is not necessary if you update AE2-UEL.

**Comment by jchung01** [comment] 2024-08-28 23:43
Also fixed the root cause with the above PR.

**Closed** 2024-08-29 04:22 UTC
