### ISSUE TITLE
weird invincibility bug after updating to latest version

### ISSUE THREAD

**Issue by RConTRS** [ACGaming/UniversalTweaks#534] opened 2024-08-12 04:15 UTC
idk why but whenever a mob attempts to damage the player with melee attack it just despawn and skeleton arrows just get reflected, player is also immune to fall damage and creeper explosion which doesn't seem to occur at all, the creeper just despawn instead of exploding.

i thought this is some bug related to log protection but im on single player and i had already removed the log prot mod.

**Comment by ACGaming** [comment] 2024-08-12 05:56
Are you certain this is directly caused by Universal Tweaks? Are you running default configs?

From my experience, this sounds like a classic case of cross-mod incompatibility.

**Comment by RConTRS** [comment] 2024-08-12 18:25
i tried downgrading UT to 1.11.0 and it completely fixed the issue, also im not running defaultconfigs

i checked the log from last time and it appears to be chaotic

[2024-08-12-6.log](https://github.com/user-attachments/files/16590483/2024-08-12-6.log)

**Comment by jchung01** [comment] 2024-08-12 18:53
Looks like I forgot a null check. Just to make sure, do you have `lastStandEnchantment` disabled in `openblocks.cfg`?

**Comment by RConTRS** [comment] 2024-08-13 14:17
![image](https://github.com/user-attachments/assets/4c493810-7afb-484d-aa16-d4a8c79e4f09)
well i do have it disabled, prob disabled it a long time ago. also sorry for long time no response my wifi can barely load curseforge

**Comment by jchung01** [comment] 2024-08-13 17:12
Should be fixed in next update - for now you can set `Last Stand Trigger Fix` to false in `Universal Tweaks - Mod Integration.cfg` as you are not using Last Stand.

**Closed** 2024-08-14 06:15 UTC
